print("Welcome to tip calculator!")
bill = float(input("What was the total bill?"))
tip = int(input("How much tip would you like to give? 10, 12, or 15?"))
person = int(input("How many people to split the bill?"))
perhead = round((bill * (1+tip/100))//person, 2)
print("Each person should pay: " + str(perhead))
